-- Add FeedbackQueue as a featured paid member.
-- Requires supabase/payment-migration.sql and supabase/paid-member-benefits-migration.sql.

INSERT INTO users (
  id,
  name,
  email,
  image,
  is_admin,
  banned,
  is_bot,
  plan,
  subscription_status,
  profile_headline,
  profile_bio,
  profile_website_url,
  profile_demo_url,
  profile_x_url,
  profile_cta_label,
  profile_cta_url,
  profile_show_contact,
  profile_weekly_digest_opt_in,
  profile_featured_category,
  email_verified_at,
  created_at
) VALUES (
  'fdb00000-0000-4000-8000-000000000001',
  'FeedbackQueue',
  'paid.feedbackqueue@likelyr.local',
  'https://feedbackqueue.dev/falcion-logo.png',
  FALSE,
  FALSE,
  FALSE,
  'pro',
  'active',
  'Structured peer feedback for indie hackers shipping SaaS, landing pages, and side projects.',
  'FeedbackQueue helps builders earn and spend credits for rubric-based reviews from other indie hackers, with AI quality scoring and human moderation to keep feedback useful.',
  'https://feedbackqueue.dev/',
  'https://feedbackqueue.dev/',
  'https://twitter.com/feedbackqueue',
  'Get feedback',
  'https://feedbackqueue.dev/',
  TRUE,
  TRUE,
  'SaaS',
  NOW(),
  NOW()
) ON CONFLICT (email) DO UPDATE SET
  name = EXCLUDED.name,
  image = EXCLUDED.image,
  is_admin = FALSE,
  banned = FALSE,
  is_bot = FALSE,
  plan = EXCLUDED.plan,
  subscription_status = EXCLUDED.subscription_status,
  profile_headline = EXCLUDED.profile_headline,
  profile_bio = EXCLUDED.profile_bio,
  profile_website_url = EXCLUDED.profile_website_url,
  profile_demo_url = EXCLUDED.profile_demo_url,
  profile_x_url = EXCLUDED.profile_x_url,
  profile_cta_label = EXCLUDED.profile_cta_label,
  profile_cta_url = EXCLUDED.profile_cta_url,
  profile_show_contact = EXCLUDED.profile_show_contact,
  profile_weekly_digest_opt_in = EXCLUDED.profile_weekly_digest_opt_in,
  profile_featured_category = EXCLUDED.profile_featured_category,
  email_verified_at = COALESCE(users.email_verified_at, EXCLUDED.email_verified_at);

INSERT INTO ideas (
  id,
  user_id,
  name,
  pitch,
  target_customer,
  problem,
  revenue_model,
  category,
  stage,
  elo_score,
  wins,
  losses,
  created_at
) VALUES (
  'fdb00000-0000-4000-8000-000000000002',
  (SELECT id FROM users WHERE email = 'paid.feedbackqueue@likelyr.local'),
  'FeedbackQueue',
  'Peer review exchange where indie hackers review each other''s SaaS, landing pages, and side projects to earn credits for structured feedback.',
  'Indie hackers and solo SaaS founders',
  'Founders finish building but struggle to get specific, trustworthy feedback without begging in communities or settling for vague praise.',
  'Free credit exchange plus paid credit plans starting at $19.99 per month',
  'SaaS',
  'Launched',
  1125,
  0,
  0,
  NOW()
) ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  name = EXCLUDED.name,
  pitch = EXCLUDED.pitch,
  target_customer = EXCLUDED.target_customer,
  problem = EXCLUDED.problem,
  revenue_model = EXCLUDED.revenue_model,
  category = EXCLUDED.category,
  stage = EXCLUDED.stage,
  elo_score = EXCLUDED.elo_score;
