-- Launch inventory for Likelyr.
-- Safe to run after schema.sql. These rows are anonymous and can be edited/deleted later.

INSERT INTO ideas (name, pitch, target_customer, problem, revenue_model, category, stage) VALUES
('LeadSniper AI', 'Finds local businesses with weak websites and drafts personalized outreach.', 'Freelance web designers and small agencies', 'Prospecting takes hours and most cold emails are generic.', '$49/month SaaS subscription', 'AI', 'MVP'),
('QuietCRM', 'A lightweight CRM for solo consultants who hate sales software.', 'Independent consultants', 'Most CRMs are too bloated for one-person businesses.', '$12/month subscription', 'SaaS', 'Launched'),
('TutorCredits', 'Students earn credits by helping classmates and spend credits when stuck.', 'College STEM students', 'Tutoring is expensive and peer help is fragmented.', '10% fee on purchased credit packs', 'Education', 'Idea'),
('ReceiptRadar', 'Turns messy contractor receipts into job-level profit reports.', 'Small home service contractors', 'Owners do not know which jobs are actually profitable.', '$29/month subscription', 'Local Business', 'MVP'),
('ClipForge', 'Repurposes long creator videos into short clips with hooks and captions.', 'Podcasters and YouTubers', 'Creators leave distribution on the table because editing clips is tedious.', '$39/month subscription', 'Creator Tools', 'MVP'),
('CartRescue SMS', 'Abandoned-cart recovery built for tiny Shopify stores.', 'Small e-commerce merchants', 'Email recovery is saturated and complex tools are expensive.', 'Usage-based SMS fees plus $19/month', 'E-commerce', 'Launched'),
('FounderRoast', 'Anonymous founder feedback that ranks the harshest useful advice.', 'Early-stage founders', 'Friends are too polite and investors are too busy.', '$9 per feedback batch', 'Wild Ideas', 'Idea'),
('TabTamer', 'Chrome extension that auto-groups tabs by project and deadline.', 'Knowledge workers with tab overload', 'Browser tabs become a hidden task manager.', '$3/month pro version', 'Chrome Extension', 'MVP'),
('VenuePulse', 'Predicts slow nights for restaurants and suggests local promotions.', 'Independent restaurants', 'Restaurants react too late to weak demand.', '$79/month per location', 'Local Business', 'Idea'),
('InvoiceNudge', 'Automated payment follow-ups that sound human for freelancers.', 'Freelancers and agencies', 'Late invoices damage cash flow and awkward follow-up wastes time.', '$15/month subscription', 'SaaS', 'Launched'),
('MicroMentor', 'Ten-minute expert calls for tactical business questions.', 'First-time founders', 'Mentorship is hard to schedule and often too broad.', '20% marketplace take rate', 'Marketplace', 'Idea'),
('LandingLens', 'Scores landing pages and writes concrete conversion fixes.', 'Indie hackers and SaaS founders', 'Founders ship vague landing pages and do not know what to change.', '$19/report or $29/month', 'AI', 'MVP'),
('ClassCapsule', 'Turns lecture recordings into quizzes and spaced repetition cards.', 'College students', 'Students record lectures but rarely review them effectively.', '$8/month student subscription', 'Education', 'MVP'),
('NicheScout', 'Finds underserved subreddit and forum pain points for product ideas.', 'Indie founders', 'Founders build from guesses instead of repeated complaints.', '$29/month subscription', 'AI', 'MVP'),
('ShiftSwap Local', 'Shift-swapping marketplace for hourly workers at nearby businesses.', 'Retail and restaurant workers', 'Managers handle shift swaps manually in group chats.', 'Employer subscription', 'Marketplace', 'Idea'),
('PixelProof', 'Visual QA screenshots for small web agencies before client delivery.', 'Small web agencies', 'Tiny responsive bugs hurt trust and are easy to miss.', '$25/month per agency', 'SaaS', 'MVP'),
('SponsorMatch', 'Matches small newsletters with niche sponsors under $500.', 'Newsletter operators', 'Small newsletters are ignored by sponsor marketplaces.', '15% transaction fee', 'Marketplace', 'MVP'),
('MenuMargin', 'Analyzes restaurant menus and flags low-margin items.', 'Independent restaurant owners', 'Menu pricing is emotional and rarely updated.', '$49/month subscription', 'Local Business', 'Idea'),
('CreatorCRM Lite', 'Relationship tracker for creators managing brands and collaborators.', 'Creators with sponsorships', 'Brand conversations live across email, DMs, and spreadsheets.', '$15/month subscription', 'Creator Tools', 'MVP'),
('RefundGuard', 'Flags risky refund patterns for small online stores.', 'Shopify merchants', 'Fraudulent refund requests are hard to identify manually.', '$29/month plus usage', 'E-commerce', 'Idea'),
('PromptPolicies', 'Company prompt library with approvals and usage rules.', 'Small teams adopting AI', 'Teams paste sensitive data into unreviewed AI prompts.', '$6/user/month', 'AI', 'Launched'),
('NeighborDesk', 'Booking and payments for neighborhood handymen.', 'Local handymen and homeowners', 'Small service providers rely on texts and cash.', '3% booking fee', 'Local Business', 'MVP'),
('ScholarSprint', 'Application tracker for scholarships with reusable essays.', 'High school seniors', 'Scholarship applications are repetitive and scattered.', '$29 one-time student plan', 'Education', 'Idea'),
('BoardBrief', 'Turns company metrics into investor update drafts.', 'Seed-stage founders', 'Investor updates are valuable but easy to postpone.', '$19/month subscription', 'SaaS', 'MVP'),
('ThreadChef', 'Converts messy notes into X and LinkedIn post threads.', 'Founders building in public', 'Good updates die in notes apps.', '$12/month subscription', 'Creator Tools', 'Launched'),
('LocalLoyalty', 'Punch-card loyalty app that works through SMS, not downloads.', 'Coffee shops and salons', 'Customers do not want another loyalty app.', '$39/month per location', 'Local Business', 'MVP'),
('ReviewReply Pro', 'Drafts on-brand replies to Google reviews for service businesses.', 'Local service businesses', 'Owners ignore reviews or reply emotionally.', '$19/month per location', 'AI', 'MVP'),
('ShipScore', 'Ranks side projects by launch readiness and missing trust signals.', 'Indie hackers', 'Builders launch before their product is understandable.', '$9/report', 'SaaS', 'Idea'),
('ChromeCoach', 'Browser extension that teaches shortcuts based on repeated actions.', 'Office workers', 'People waste time because software training is generic.', '$4/month pro version', 'Chrome Extension', 'Idea'),
('ReturnRabbit', 'Self-serve returns portal for tiny apparel brands.', 'Small apparel stores', 'Returns are handled manually through email.', '$29/month plus return volume', 'E-commerce', 'MVP'),
('SkillAuction', 'Marketplace where experts auction one-hour office hours.', 'Operators and founders', 'Expert access is opaque and scheduling takes too long.', '20% marketplace take rate', 'Marketplace', 'Idea'),
('FocusReceipts', 'Tracks time spent in distracting sites and attaches a daily cost.', 'Remote workers', 'Screen time stats do not connect distraction to money.', '$5/month subscription', 'Chrome Extension', 'MVP'),
('PodcastPilot', 'Finds podcast guest opportunities and drafts pitches.', 'B2B founders', 'Podcast outreach is manual and poorly targeted.', '$49/month subscription', 'AI', 'MVP'),
('RosterRocket', 'Simple scheduling for youth sports volunteers.', 'Youth sports leagues', 'Parents coordinate through chaotic text threads.', '$99/season per team', 'Consumer App', 'Idea'),
('TinyTerms', 'Plain-English contract explainer for freelancers.', 'Freelancers signing client contracts', 'Freelancers do not understand legal risk before signing.', '$15/document', 'AI', 'MVP'),
('PortfolioPing', 'Alerts designers when portfolio links break or screenshots age.', 'Freelance designers', 'Portfolios quietly rot and hurt inbound leads.', '$6/month subscription', 'SaaS', 'Idea'),
('WaitlistWager', 'Lets users bet points on which upcoming product will win its category.', 'Product enthusiasts', 'Waitlists are passive and boring.', 'Sponsored tournaments', 'Wild Ideas', 'Idea'),
('CourseCorrect', 'Shows creators where students drop off inside recorded courses.', 'Online course creators', 'Creators do not know which lessons lose students.', '$39/month subscription', 'Education', 'MVP'),
('Stockroom Snap', 'Photo-based inventory counts for tiny retailers.', 'Boutique retail shops', 'Manual inventory counts are slow and inaccurate.', '$49/month subscription', 'Local Business', 'Idea'),
('BugBounty Lite', 'Tiny public bug bounty pages for indie SaaS products.', 'Indie SaaS founders', 'Security feedback arrives through random DMs.', '$19/month subscription', 'SaaS', 'MVP'),
('GiftGraph', 'Gift recommendations based on a friend''s public posts.', 'Busy gift buyers', 'Generic gift guides miss the actual person.', 'Affiliate revenue', 'Consumer App', 'Idea'),
('ResumeReceipts', 'Tracks job applications and gives honest funnel analytics.', 'Job seekers', 'Applicants do not know whether their resume or interview is failing.', '$9/month subscription', 'Consumer App', 'Launched'),
('CreatorInvoice', 'Invoices and payment reminders built for brand deals.', 'Micro-creators', 'Creators handle paid collaborations in spreadsheets.', '$12/month subscription', 'Creator Tools', 'MVP'),
('SaaSChurn Notes', 'Collects cancellation reasons and clusters them into roadmap themes.', 'Early SaaS teams', 'Cancellation feedback is scattered and underused.', '$49/month subscription', 'SaaS', 'MVP'),
('HomeQuote Compare', 'Normalizes contractor quotes so homeowners can compare line items.', 'Homeowners hiring contractors', 'Quotes are impossible to compare apples-to-apples.', '$15 per project', 'Consumer App', 'Idea'),
('DMDesk', 'Shared inbox for creators selling through Instagram DMs.', 'Social commerce sellers', 'Orders get lost inside social DMs.', '$29/month subscription', 'Creator Tools', 'MVP'),
('MeetCute Map', 'Opt-in map of low-pressure local singles events.', 'Urban singles tired of dating apps', 'Dating apps are high-friction and low-trust.', 'Event affiliate fees', 'Consumer App', 'Idea'),
('LaunchLedger', 'Tracks every launch channel and ranks ROI by signup quality.', 'Indie founders', 'Founders do not know which launch channels create real users.', '$19/month subscription', 'SaaS', 'Idea'),
('AI Policy Bot', 'Slack bot that answers company AI usage policy questions.', 'Operations leaders', 'Employees do not read policy docs before using AI tools.', '$3/user/month', 'AI', 'MVP'),
('CraftCart', 'Simple storefronts for local makers selling at markets.', 'Local craft vendors', 'Market vendors need lightweight commerce without Shopify complexity.', '$15/month subscription', 'E-commerce', 'Idea');
